steps:
- name: 'gcr.io/${PROJECT_ID}/firebase'
  args: [ 'deploy', '--project', '${PROJECT_ID}', '--token', '$$FIREBASE_TOKEN', '--only', 'firestore:rules']
  secretEnv: ['FIREBASE_TOKEN']
  
secrets:
- kmsKeyName: 'projects/x-dev-ew3/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: 'CiQA8wnE9KTrzGYDLUjZnQfeDUuMhNGp+eB/I46cNQzzhpJdYZkSbwBYl1a7lsbVs7qGyVGdZSjY
WeqlEm3d/am5L2qFAeA5dqZy4nVGQUj0/OWfdNxwP4EE14IGtvWPNGZKh1judjscsim+iUz0NpIg
m6TB7MqGQvOqCFpe1I0MfI9Hn0C32PYttB91kQgr2CB/+FS/wA=='
